# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ac53734856614e1cd78753181ac5ed810644f09763256757cd1e6696f0646e092d98d0ca5a1f3ee9470fe0220d9eeb46981557b9b0b78da83b7d9990d75738e

test:
  secret_key_base: 2bee09ea363f97f0932dd45014ab5b499eb7b07a1fb6c4c973c9af3d347f850bf0c84520e5762e83b9fee6c8d5655aa0f2f1dd5ab070b5203ab1fb4ab4ca2396

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
